name: jakerye-learn-snapcraft-flask 
base: core18
version: '1.0.0'
summary: Learn snapcraft with python flask app
description: |
  This is the a very simple snap that displays hello world on webpage server via 
  python flask It hosts on port 5000. The easiest way to expose it is via serveo.

grade: stable 
confinement: strict

apps:
  jakerye-learn-snapcraft-flask:
    command: flask run
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
    environment:
      FLASK_APP: hello.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

parts:
  flask-app:
    source: .
    plugin: python
    python-version: python3
