name: jakerye-learn-snapcraft-flask 
version: '1.0.0'
summary: Learn snapcraft with python flask app
description: |
  This is the a very simple snap that displays hello world on webpage server via 
  python flask.

grade: devel 
confinement: devmode

apps:
  jakerye-learn-snapcraft-flask:
    command: flask run
    environment:
      FLASK_APP: hello.py
    plugs: [network-bind]

parts:
  flask-app:
    source: .
    plugin: python
    python-version: python3


# https://github.com/jakerye/learn-snapcraft-python.git
# source-tag: v1.1.3
# daemon: simple
# restart-condition: always